# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 196e66d086783f006349ce1a0b39aac84f8bb72c32d860c415b1c48cf26aae64fffa4efda6978adaaf4238d4f7546ddf58fa4b766520f472ca107e6cd15d2871

test:
  secret_key_base: 4daa5ced789aac2dc30e2ee3d6f63a303d09544e3ca0d97c8fd601c90182f4bff7791314468afe1cc53bc64037c6efd1ca9dd3f160ef946fdda68f0d53ed3e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
