# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a995933032bcd1b06f71c3c46e07b3730eb58558abfc8100c8557d7dfd8e37c597116cc114d6258a715e182acbe8934b164c73cd6b69756fa15a2774a2e76bf5

test:
  secret_key_base: 121a14123ea4e6b50cb25fe3b97f4285fb48adfd044c3ca7c31f9a38ff9c99e28e0c4547996c5dfb45ecebaba57979e7edfa3c522e0cbd6cc96af20ef43e4166

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
