# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af4dfc31732e0de528f03d9d3c5f5e628184a4dddd3286e344142b0b8d272a65dba76c45df6f20a5ca1e54e031e6b5ec9fe46ce043fecd9e6a8c0339d7cbe6ab

test:
  secret_key_base: 3c9537b13c4f6b768a825ea8da85753f9a16451b005826b7e6e9bac8e49ab421a1f8ad5c42b2f4a8814f8f0455cb808b2841f37ded5237c944cf602bcaddb77a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
